---
- name: add brightbox ppa for ruby
  apt_repository:
    repo: 'ppa:brightbox/ruby-ng-experimental'
    update-cache: yes
    state: present

- name: install ruby
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
  with_items:
    - "ruby{{ ruby_version }}"
    - ruby-switch

- name: install ruby-dev
  apt:
    pkg: "ruby{{ ruby_version }}-dev"
    state: present
    update-cache: yes
  when: ruby_dev

- name: install ruby-doc
  apt:
    pkg: "ruby{{ ruby_version }}-doc"
    state: present
    update-cache: yes
  when: ruby_doc

- name: set ruby as default
  shell: "ruby-switch --set ruby{{ ruby_version }}"

- name: install bundler
  gem:
    name: bundler
    user_install: no
