---
- name: add brightbox ppa for ruby
  apt_repository:
    repo: 'ppa:brightbox/ruby-ng-experimental'
    update-cache: yes
    state: present

- name: install ruby
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
  with_items:
    - "ruby{{ ruby_version }}"
    - ruby-switch

- name: install ruby-dev
  apt:
    pkg: "ruby{{ ruby_version }}-dev"
    state: present
    update-cache: yes
  when: ruby_dev

- name: install ruby-doc
  apt:
    pkg: "ruby{{ ruby_version }}-doc"
    state: present
    update-cache: yes
  when: ruby_doc

- name: check default ruby version
  shell: "ruby-switch --check | grep ruby{{ ruby_version }}"
  register: check_ruby_version
  changed_when: no
  check_mode: no

- name: set ruby as default
  shell: "ruby-switch --set ruby{{ ruby_version }}"
  when: check_ruby_version['rc'] == '1'

- name: install bundler
  gem:
    name: bundler
    version: "{{ bundler_version }}"
    user_install: no
